apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-po
  name: my-po
spec:
  serviceAccountName: build-robot
  containers:
  - image: nginx
    name: my-po
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
